import cv2,os
logo=cv2.imread("opencv-assets-main\opencv.png")
print(logo.shape)
cv2.imshow("logo",logo)
cv2.waitKey(0)
logo2=cv2.imread("opencv-assets-main\opencv.png",0)
cv2.imshow("logo2",logo2)
cv2.waitKey(0)
os.chdir("C:/Aahana/")
cv2.imwrite("logogrey.png",logo2)
logo3=cv2.cvtColor(logo2,cv2.COLOR_GRAY2BGR)
print(logo3.shape)
logo3_color=cv2.applyColorMap(logo3,cv2.COLORMAP_VIRIDIS)
cv2.imshow("logo3",logo3_color)
cv2.waitKey(0)